config/routes.rb
Rails.application.routes.draw do
  resources :search, only: %i[index] do
    post :find, on: :collection
  end

  root "search#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :recipes

  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :ingredients

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index; end

  def find
    @recipes = Recipe.includes(:ingredients).all

    params["included"].select(&:present?).each do |included|
      @recipes = @recipes.where(ingredients: { name: included })
    end

    params["excluded"].select(&:present?).each do |excluded|
      @recipes = @recipes.where.not(ingredients: { name: excluded })
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tom-select/dist/css/tom-select', "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 w-5/6">
      <%= yield %>
    </main>
  </body>
</html>

app/views/search/find.turbo_stream.erb
<%= turbo_stream.replace "search_results" do %>
  <%= turbo_frame_tag "search_results" do %>
    <% @recipes.each do |recipe| %>
      <div class="my-4 flex w-full space-x-4">
        <div class="w-32">
          <img src="<%= recipe.thumbnail %>" alt="<%= recipe.name %>"/>
        </div>

        <div class="w-2/5">
          <a class="text-blue-500" href="<%= recipe.url %>"><%= recipe.name %></a>
        </div>

        <div class="w-2/5">
          <ul>
            <% recipe.ingredients.each do |ingredient| %>
              <li><%= ingredient.name %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/search/index.html.erb
<%= form_with url: find_search_index_path, class: "w-full" do |f| %>
  <div class="flex space-x-4 w-full">
    <div class="w-1/2" data-controller='tom-select'>
      <%= f.label :included, "I'm really in for ..." %>
      <%= f.select :included, Ingredient.order(:name).pluck(:name), { include_blank: true }, { multiple: true } %>
    </div>

    <div class="w-1/2" data-controller='tom-select'>
      <%= f.label :excluded, "Go away with ..." %>
      <%= f.select :excluded, Ingredient.order(:name).pluck(:name), { include_blank: true }, { multiple: true, data: { controller: 'tom-select' } } %>
    </div>
  </div>

  <button class="bg-gray-200 hover:bg-gray-500 text-gray-700 font-bold py-2 px-4 my-4 rounded" >Get me some ideas!</button>
<% end %>

<%= turbo_frame_tag "search_results", class: "w-full" %>